### ISSUE TITLE
May I ask if you try to use a backbone with a multi-branch structure in ClusterContrast USL ReID?

### ISSUE THREAD

**Issue by Trangle12** [RikoLi/WACV23-workshop-TMGF#5]
Thanks for your work on ReID! I have a few questions:
      1、I would like to ask if this combination of global and local vit as backbone has been tried at ClusterContrtast?
      2、When calculating the contrastive loss in ClusterContrtast, the features [n_part, batch, c] are used to crossentropy loss should the 
            loss be calculated together or separately for each part loss?

Looking forward to your generous help!

**Comment by RikoLi** [comment]
Hi Trangle12, thank you for your attention on our work!
1. We tried ClusterContrast in early experiments, which shows lower performance than our online-offline loss.
2. Part losses can be calculated in paralleled wise with the global loss. You can refer to Eq.9 in the paper and [implementation code](https://github.com/RikoLi/WACV23-workshop-TMGF/blob/main/libs/models/mb.py) for details.
